### PR TITLE
[Feature] Improvements for toggle icon to align with style guide

### PR DESCRIPTION
**Pull request by aappoalander**
## Features
Improvements for toggle icon so that implementation matches style guide and works smoothly
- Improved toggle shadow for better visibility
- Symmetric movement of toggle knob
- Change for unchecked toggle color

### CODE REVIEW

**Comment by ketsappi** [comment]
Is the knob intentionally also moved vertically up a little?

**Before (upper) & after (lower)**
toggle_icon_difference

**Comment by aappoalander** [comment]
> Is the knob intentionally also moved vertically up a little?
> 
> **Before (upper) & after (lower)**
> toggle_icon_difference

Not sure how this was tested, but the related upcoming PR for ui-components includes changes to css as well and does not seem to have this issue when used with this PR.

align

**Comment by ketsappi** [comment]
> Not sure how this was tested, but the related upcoming PR for ui-components includes changes to css as well and does not seem to have this issue when used with this PR.

Did not have knowledge of the upcoming PR for ui-components and that it will have also CSS changes regarding this.
It was tested by updating the icons-dependency to local cmp and comparing the Toggle components; local vs [released dev](https://vrk-kpa.github.io/suomifi-ui-components/dev/#/Components/Primitive/Toggle)

**Review by ketsappi — APPROVED** [review]

**Comment by aappoalander** [comment]
> > Not sure how this was tested, but the related upcoming PR for ui-components includes changes to css as well and does not seem to have this issue when used with this PR.
> 
> Did not have knowledge of the upcoming PR for ui-components and that it will have also CSS changes regarding this.
> It was tested by updating the icons-dependency to local cmp and comparing the Toggle components; local vs [released dev](https://vrk-kpa.github.io/suomifi-ui-components/dev/#/Components/Primitive/Toggle)

Also tested the component icon out-of-the-box without the ui-components styles (this is the only thing really exported by this repo) and seems to be working.

Näyttökuva 2020-5-25 kello 9 20 39

**Pull request merged**
